---
title: "Admission Statistics Analysis"
author: "Anderson Monken and Douglas Neumann"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(plotly)
library(tidyverse)
library(rpart)
library(rattle)
library(tree)
library(visNetwork)
library(sparkline)

source('./data_cleaning.R')
```

Background
========================================================

Column
-------------------------------------

### Headline Stats

<center>
<h4> Acceptance Rate: <b>36%</b> </h4>
<h4> Students admitted: <b>29</b> </h4>
<h4> States Represented in Class: <b>4</b> </h4>
<h4> Average GPA: <b>3.74</b> </h4>
<h4> Average Test Score: <b>960</b> </h4>
<h4> Female Representation: <b>45%</b> </h4>
</center>

### Inititial Decision Bar Graph

```{r, echo = FALSE}
# Simple Horizontal Bar Plot with Added Labels

ggplotly(
ggplot(df %>% group_by(Decision) %>% tally(), 
       aes(x = Decision, y = n, fill = Decision)) + 
  geom_col(aes(text=sprintf("Count: %s<br>Decision: %s", n, Decision))) + 
  ggtitle("Decision Distribution") + 
  xlab("Decision") +
  ylab("Count") +
  scale_fill_manual(values = c('#F8766D','#619CFF','#00BA38'), breaks = c('Decline','Waitlist','Admit')) +
           theme_classic(),

tooltip="text"
)
```


Column
-------------------------------------

### GPA

```{r, echo = FALSE}
ggplotly(ggplot(data = df, aes(x = GPA)) + geom_density(aes(fill = Decision), alpha = 0.5) + 
           scale_fill_manual(values = c('#F8766D','#619CFF','#00BA38'), breaks = c('Decline','Waitlist','Admit')) +
           theme_classic())
```

Column
-------------------------------------

### Work Experience

```{r, echo = FALSE}
ggplotly(ggplot(data = df, aes(x = WorkExp)) + geom_density(aes(fill = Decision), alpha = 0.5) +
           scale_fill_manual(values = c('#F8766D','#619CFF','#00BA38'), breaks = c('Decline','Waitlist','Admit')) +
           theme_classic())
```


State Effects
========================================================

```{r, echo = FALSE}

state_order <- df %>% group_by(State) %>% tally()%>% arrange(n) %>% pull(State)

state_plot_data <- df %>% group_by(State, Decision) %>% tally() %>% mutate(Decision = factor(Decision, levels = c('Admit','Waitlist','Decline')), State = factor(State, state_order))

ggplotly(
  
ggplot(data = state_plot_data, 
       aes(x = State, y = n, color = Decision, fill = Decision)) + 
  geom_col() + 
  theme_classic() + 
  coord_flip() + 
  scale_fill_manual(values = c('#F8766D','#619CFF','#00BA38'), breaks = c('Decline','Waitlist','Admit')) +
  scale_color_manual(values = c('#F8766D','#619CFF','#00BA38'), breaks = c('Decline','Waitlist','Admit')) +
  ggtitle("Admission Decision by State")
         
)
```


Score Effects
========================================================


Column
-------------------------------------

### Test Score

```{r, echo = FALSE}
renderPlotly({ggplotly(
  
  ggplot(data = df, aes(x = TestScore)) + 
    geom_density(aes(fill = Decision), alpha = 0.5) + 
    scale_fill_manual(values = c('#F8766D','#619CFF','#00BA38'), breaks = c('Decline','Waitlist','Admit')) +
    theme_classic()
)
})
```

Column
-------------------------------------

### Writing Score

```{r, echo = FALSE}
renderPlotly({ggplotly(
  
  ggplot(data = df, aes(x = WritingScore)) + 
    geom_density(aes(fill = Decision), alpha = 0.5) + 
    scale_fill_manual(values = c('#F8766D','#619CFF','#00BA38'), breaks = c('Decline','Waitlist','Admit')) +
    theme_classic()
)
})
```





Gender Effects
========================================================

```{r, echo = FALSE}
ggplotly(ggplot(data = df %>% group_by(Gender, Decision) %>% tally(), aes(x = Gender, y = n, color = Decision, fill = Decision)) + geom_col() + theme_classic())
```


Volunteer Effects
========================================================

### Volunteer plot

```{r, echo = FALSE}

VolunteerLevel_order <- df %>% group_by(VolunteerLevel) %>% tally()%>% arrange(n) %>% pull(VolunteerLevel)

VolunteerLevel_plot_data <- df %>% group_by(VolunteerLevel, Decision) %>% tally() %>% mutate(Decision = factor(Decision, levels = c('Admit','Waitlist','Decline')), VolunteerLevel = factor(VolunteerLevel, VolunteerLevel_order))

ggplotly(
  
ggplot(data = VolunteerLevel_plot_data, 
       aes(x = VolunteerLevel, y = n, color = Decision, fill = Decision)) + 
  geom_col() + 
  theme_classic() + 
  coord_flip() + 
  scale_fill_manual(values = c('#F8766D','#619CFF','#00BA38'), breaks = c('Decline','Waitlist','Admit')) +
  scale_color_manual(values = c('#F8766D','#619CFF','#00BA38'), breaks = c('Decline','Waitlist','Admit')) +
  ggtitle("Admission Decision by Volunteer Level")
         
)
```


Decision Tree
=========================================================


### Decision Tree

```{r, echo = FALSE}
tree_simple <- rpart(Decision ~ ., data=df, cp =0.000000005)
#decision_tree_prez <- fancyRpartPlot(tree_simple, main = 'Decision Tree of Admissions\n\n', sub = NA)

visTree(tree_simple, main = "Decision Tree")

```
